# Generated by Django 5.1.4 on 2024-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
