# Generated by Django 5.1.4 on 2024-12-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_collection_name_moviecollection_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecollection',
            name='is_active',
        ),
    ]
